package com.fs.twitchminichat

import java.security.SecureRandom

/** Untrusted values extracted from an Android OAuth callback URI. */
internal data class OAuthCallbackInput(
    val isHierarchical: Boolean,
    val scheme: String?,
    val host: String?,
    val port: Int,
    val path: String?,
    val userInfo: String?,
    val fragment: String?,
    val loginTokens: List<String>,
    val slots: List<String>
)

/** Validated values required to finalize one pending Android OAuth request. */
internal data class OAuthCallbackPayload(
    val loginToken: String,
    val slot: Int
)

/**
 * Applies fail-closed validation to OAuth callback and finalization data.
 *
 * Callback Uniform Resource Identifier (URI) values are attacker-controlled even
 * when Android selected this application for the custom scheme. The backend response
 * remains the only trusted source for account identity and session credentials.
 */
internal object OAuthFlowSecurityPolicy {

    /** Maximum time an Android browser login may remain pending. */
    const val PENDING_REQUEST_TTL_MS = 10L * 60L * 1000L

    /** Small tolerance for a device clock adjustment immediately after login starts. */
    private const val MAX_FUTURE_CLOCK_SKEW_MS = 60L * 1000L

    /** Defensive upper bound for the opaque one-time backend login token. */
    private const val MAX_LOGIN_TOKEN_LENGTH = 2048

    /** Defensive upper bound for backend identity and credential fields. */
    private const val MAX_BACKEND_FIELD_LENGTH = 8192

    /** Returns a callback payload only when origin and critical parameters are valid. */
    fun validateCallback(
        input: OAuthCallbackInput,
        expectedScheme: String
    ): OAuthCallbackPayload? {
        if (!input.isHierarchical) return null
        if (!input.scheme.equals(expectedScheme, ignoreCase = true)) return null
        if (!input.host.equals(EXPECTED_CALLBACK_HOST, ignoreCase = true)) return null
        if (input.port != -1) return null
        if (input.path != null && input.path.isNotEmpty() && input.path != "/") return null
        if (input.userInfo != null || input.fragment != null) return null
        if (input.loginTokens.size != 1 || input.slots.size != 1) return null

        val loginToken = input.loginTokens.single()
        if (!isValidOpaqueLoginToken(loginToken)) return null

        val slotText = input.slots.single()
        if (slotText != slotText.trim()) return null

        val slot = slotText.toIntOrNull()
            ?.takeIf(::isValidAndroidSlot)
            ?: return null

        return OAuthCallbackPayload(
            loginToken = loginToken,
            slot = slot
        )
    }

    /** Returns true only while locally persisted OAuth metadata is fresh. */
    fun isPendingRequestFresh(createdAtEpochMs: Long, nowEpochMs: Long): Boolean {
        if (createdAtEpochMs <= 0L || nowEpochMs <= 0L) return false

        val ageMs = nowEpochMs - createdAtEpochMs
        return ageMs in -MAX_FUTURE_CLOCK_SKEW_MS..PENDING_REQUEST_TTL_MS
    }

    /**
     * Accepts a finalization response only when it is bound to the consumed request
     * and contains the complete backend-authoritative identity and session.
     */
    fun isValidFinalizeResult(
        pendingRequest: OAuthPendingRequest,
        result: OAuthFinalizeResult
    ): Boolean {
        if (result.slot != pendingRequest.slot) return false
        if (!isValidAndroidSlot(result.slot)) return false

        return listOf(
            result.profileId,
            result.username,
            result.userId,
            result.accessToken,
            result.desktopSessionToken
        ).all(::isValidBackendField)
    }

    /** Returns true for slots generated by the Android integer callback contract. */
    fun isValidAndroidSlot(slot: Int): Boolean = slot > 0

    /** Validates a non-secret backend field without recording or transforming it. */
    private fun isValidBackendField(value: String): Boolean {
        return value.isNotBlank() &&
            value.length <= MAX_BACKEND_FIELD_LENGTH &&
            value.none { character ->
                character.isWhitespace() || character.isISOControl()
            }
    }

    /** Validates the opaque token shape without assuming a backend encoding. */
    private fun isValidOpaqueLoginToken(value: String): Boolean {
        return value.isNotBlank() &&
            value == value.trim() &&
            value.length <= MAX_LOGIN_TOKEN_LENGTH &&
            value.none { character ->
                character.isWhitespace() || character.isISOControl()
            }
    }

    private const val EXPECTED_CALLBACK_HOST = "auth"
}

/**
 * Allocates unpredictable positive integer slots for the legacy backend contract.
 *
 * The random slot prevents the previous trivial `slot=0` callback fixation. It is
 * defense in depth and does not replace a future backend-bound 128-bit nonce or
 * Proof Key for Code Exchange (PKCE) verifier.
 */
internal class OAuthCallbackSlotAllocator(
    private val nextCandidate: () -> Int = {
        SECURE_RANDOM.nextInt(Int.MAX_VALUE - 1) + 1
    }
) {

    /** Returns an unused slot, retrying the negligible random-collision case. */
    fun allocate(isOccupied: (Int) -> Boolean): Int? {
        repeat(MAX_ALLOCATION_ATTEMPTS) {
            val candidate = nextCandidate()
            if (
                OAuthFlowSecurityPolicy.isValidAndroidSlot(candidate) &&
                !isOccupied(candidate)
            ) {
                return candidate
            }
        }

        return null
    }

    private companion object {
        /** Process-wide cryptographically strong random source. */
        private val SECURE_RANDOM = SecureRandom()

        /** Bounded retries prevent a faulty source from blocking the user interface. */
        private const val MAX_ALLOCATION_ATTEMPTS = 32
    }
}
